---
language: node_js

sudo: false

notifications:
  email: false

cache:
  directories:
    - node_modules

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g node-sass
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test
